version: '3.9'

services:
  php-apache:
    container_name: php-apache
    restart: always
    build:
      context: ./php
      args:
        - PHP_VERSION=$PHP_VERSION
    ports:
      - $APACHE_PORT:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:$MYSQL_DOCKER_IMAGE_TAG
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - $PHP_MY_ADMIN_PORT:80
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=$MYSQL_ROOT_PASSWORD
