services:
  php-apache:
    container_name: php-apache
    restart: always
    build:
      context: ./php
    ports:
      - $APACHE_PORT:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:$MYSQL_DOCKER_IMAGE_TAG
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
