version: '3.9'

services:
  php-apache:
    container_name: php-apache
    restart: always
    build:
      context: ./php
      args:
        - PHP_VERSION
    ports:
      - 127.0.0.1:${APACHE_PORT}:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:${MYSQL_DOCKER_IMAGE_TAG}
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 127.0.0.1:${PHP_MY_ADMIN_PORT}:80
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
